"""add vehicle handover reports

Revision ID: 175d87519af1
Revises: 7ab17c3e520d
Create Date: 2026-03-21 16:16:08.818645
"""

from alembic import op
import sqlalchemy as sa



revision = '175d87519af1'
down_revision = '7ab17c3e520d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_handover_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('mileage_start', sa.Integer(), nullable=True),
    sa.Column('mileage_end', sa.Integer(), nullable=True),
    sa.Column('dashboard_warnings_start', sa.Text(), nullable=True),
    sa.Column('dashboard_warnings_end', sa.Text(), nullable=True),
    sa.Column('damage_notes_start', sa.Text(), nullable=True),
    sa.Column('damage_notes_end', sa.Text(), nullable=True),
    sa.Column('notes_start', sa.Text(), nullable=True),
    sa.Column('notes_end', sa.Text(), nullable=True),
    sa.Column('has_documents', sa.Boolean(), nullable=False),
    sa.Column('has_medkit', sa.Boolean(), nullable=False),
    sa.Column('has_extinguisher', sa.Boolean(), nullable=False),
    sa.Column('has_warning_triangle', sa.Boolean(), nullable=False),
    sa.Column('has_spare_wheel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['vehicle_assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_handover_reports_assignment_id'), 'vehicle_handover_reports', ['assignment_id'], unique=True)
    op.create_index(op.f('ix_vehicle_handover_reports_id'), 'vehicle_handover_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_handover_reports_id'), table_name='vehicle_handover_reports')
    op.drop_index(op.f('ix_vehicle_handover_reports_assignment_id'), table_name='vehicle_handover_reports')
    op.drop_table('vehicle_handover_reports')
    # ### end Alembic commands ###
