"""add employee profiles

Revision ID: 389a42f58434
Revises: 73d9afc12ec8
Create Date: 2026-03-25 14:59:07.393974
"""

import sqlalchemy as sa

from alembic import op

revision = "389a42f58434"
down_revision = "73d9afc12ec8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("position", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=100), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=30), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employee_profiles_id"), "employee_profiles", ["id"], unique=False)
    op.create_index(
        op.f("ix_employee_profiles_user_id"), "employee_profiles", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_profiles_user_id"), table_name="employee_profiles")
    op.drop_index(op.f("ix_employee_profiles_id"), table_name="employee_profiles")
    op.drop_table("employee_profiles")
    # ### end Alembic commands ###
