"""initial schema

Revision ID: 73d9afc12ec8
Revises:
Create Date: 2026-03-24 19:37:36.978220
"""

import sqlalchemy as sa

from alembic import op

revision = "73d9afc12ec8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("unique_code", sa.String(length=50), nullable=False),
        sa.Column("shift_number", sa.String(length=20), nullable=True),
        sa.Column("pin_hash", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_unique_code"), "users", ["unique_code"], unique=True)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("license_plate", sa.String(length=20), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("vin", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "IN_SERVICE", "INACTIVE", "SOLD", name="vehicle_status"),
            nullable=False,
        ),
        sa.Column("current_mileage", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_plate"),
        sa.UniqueConstraint("vin"),
    )
    op.create_index(op.f("ix_vehicles_id"), "vehicles", ["id"], unique=False)
    op.create_table(
        "vehicle_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "CLOSED", name="assignment_status"), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vehicle_assignments_id"), "vehicle_assignments", ["id"], unique=False)
    op.create_index(
        op.f("ix_vehicle_assignments_user_id"), "vehicle_assignments", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_vehicle_assignments_vehicle_id"),
        "vehicle_assignments",
        ["vehicle_id"],
        unique=False,
    )
    op.create_table(
        "vehicle_handover_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("mileage_start", sa.Integer(), nullable=True),
        sa.Column("mileage_end", sa.Integer(), nullable=True),
        sa.Column("dashboard_warnings_start", sa.Text(), nullable=True),
        sa.Column("dashboard_warnings_end", sa.Text(), nullable=True),
        sa.Column("damage_notes_start", sa.Text(), nullable=True),
        sa.Column("damage_notes_end", sa.Text(), nullable=True),
        sa.Column("notes_start", sa.Text(), nullable=True),
        sa.Column("notes_end", sa.Text(), nullable=True),
        sa.Column("has_documents", sa.Boolean(), nullable=False),
        sa.Column("has_medkit", sa.Boolean(), nullable=False),
        sa.Column("has_extinguisher", sa.Boolean(), nullable=False),
        sa.Column("has_warning_triangle", sa.Boolean(), nullable=False),
        sa.Column("has_spare_wheel", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assignment_id"], ["vehicle_assignments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicle_handover_reports_assignment_id"),
        "vehicle_handover_reports",
        ["assignment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_vehicle_handover_reports_id"), "vehicle_handover_reports", ["id"], unique=False
    )
    op.create_table(
        "vehicle_issues",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=True),
        sa.Column("reported_by_user_id", sa.Integer(), nullable=False),
        sa.Column("need_service_in_km", sa.Integer(), nullable=True),
        sa.Column("need_brakes", sa.Boolean(), nullable=False),
        sa.Column("need_tires", sa.Boolean(), nullable=False),
        sa.Column("need_oil", sa.Boolean(), nullable=False),
        sa.Column("dashboard_checks", sa.Text(), nullable=True),
        sa.Column("other_problems", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "IN_PROGRESS", "RESOLVED", name="vehicle_issue_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assignment_id"], ["vehicle_assignments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reported_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicle_issues_assignment_id"), "vehicle_issues", ["assignment_id"], unique=False
    )
    op.create_index(op.f("ix_vehicle_issues_id"), "vehicle_issues", ["id"], unique=False)
    op.create_index(
        op.f("ix_vehicle_issues_reported_by_user_id"),
        "vehicle_issues",
        ["reported_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicle_issues_vehicle_id"), "vehicle_issues", ["vehicle_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vehicle_issues_vehicle_id"), table_name="vehicle_issues")
    op.drop_index(op.f("ix_vehicle_issues_reported_by_user_id"), table_name="vehicle_issues")
    op.drop_index(op.f("ix_vehicle_issues_id"), table_name="vehicle_issues")
    op.drop_index(op.f("ix_vehicle_issues_assignment_id"), table_name="vehicle_issues")
    op.drop_table("vehicle_issues")
    op.drop_index(op.f("ix_vehicle_handover_reports_id"), table_name="vehicle_handover_reports")
    op.drop_index(
        op.f("ix_vehicle_handover_reports_assignment_id"), table_name="vehicle_handover_reports"
    )
    op.drop_table("vehicle_handover_reports")
    op.drop_index(op.f("ix_vehicle_assignments_vehicle_id"), table_name="vehicle_assignments")
    op.drop_index(op.f("ix_vehicle_assignments_user_id"), table_name="vehicle_assignments")
    op.drop_index(op.f("ix_vehicle_assignments_id"), table_name="vehicle_assignments")
    op.drop_table("vehicle_assignments")
    op.drop_index(op.f("ix_vehicles_id"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_users_unique_code"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
