"""add shift number to users

Revision ID: baa856256943
Revises: 756c652910b6
Create Date: 2026-03-23 12:51:16.054252
"""

from alembic import op
import sqlalchemy as sa



revision = 'baa856256943'
down_revision = '756c652910b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shift_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shift_number')
    # ### end Alembic commands ###
