"""create vehicles table

Revision ID: e2e4e47d4cba
Revises: ecaa076ca994
Create Date: 2026-03-21 13:36:22.398812
"""

from alembic import op
import sqlalchemy as sa



revision = 'e2e4e47d4cba'
down_revision = 'ecaa076ca994'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
