"""create vehicles table

Revision ID: ecaa076ca994
Revises: 
Create Date: 2026-03-21 13:34:40.152077
"""

from alembic import op
import sqlalchemy as sa



revision = 'ecaa076ca994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_SERVICE', 'INACTIVE', 'SOLD', name='vehicle_status'), nullable=False),
    sa.Column('current_mileage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
